### ISSUE TITLE
Taskbar disappears when I right click a tray icon

### ISSUE THREAD

**Issue by TotalEclipse08** [CrypticButter/ButteryTaskbar#12]
Hi there, just wondering if this was intentional? 

Whenever I click on a tray icon the taskbar will disappear and more often than not the right click will not actually register.

Any help would be appreciated.

Thanks

**Comment by LuisThiamNye** [comment]
I assume that is because the Start menu closes when you click there. If I remember well, I think I worked around this by moving the tray icons into the overflow menu (ie making the icons hidden).

Yes see https://github.com/CrypticButter/ButteryTaskbar/wiki/Installation,-Setup-and-Usage#configuring-windows
