### ISSUE TITLE
Couldn't it implement the "pressure" idea from your blog? (Or enable regular mouse interaction)

### ISSUE THREAD

**Issue by m-7761** [CrypticButter/ButteryTaskbar#8]
I'd like to give this a try, but I'm curious why disable mouse access? I've always used the wide vertical taskbar and the solution Microsoft came up with to disable the SetForegroundWindow API (make taskbar blink orange every time you start an app and for reasons sometimes just hang there not blinking orange so we have to try every item in the taskbar) is just broken for this in Windows 10 these days. I don't think anyone tests or knows about the wide vertical taskbar, it seems. Even the Win Key doesn't seem to make it stay down (only temporarily) so I'm trying to find a more drastic solution today.

(If you think mouse can work I don't mind adding the feature. I do C++ development every day for two decades, and Win32 but C# is a language I don't work in, with lots of pitfalls and maybe not great access, but if I can write something in C++ and link it in I wouldn't mind learning. Or if you can recommend system APIs that will work with C# I can do the work. I've hacked C# projects before.)

**Comment by LuisThiamNye** [comment]
_(I am no longer developing the app since Windows irritated me too much, so it has been a long time since I touched the code. Looking back, it's quite messy code.)_

I agree, it would be great to have pressure-sensing working. This would get around the issue of accidentally showing the taskbar without destroying mouse access altogether.

The reason I haven't implemented it is because of the extra complexity and I had a bad enough time trying to figure out how to use the poorly documented low-level API for dealing with the taskbar and Start menu without prior experience. Ultimately, binding the Windows key to a button on my mouse was enough to satisfy my needs — faster than moving the cursor to the edge of the screen too. Alt-tab is faster yet.

If the feature means enough to you, feel free to work on a solution. Just note that I can't really afford to spend much time on this program.

**Comment by m-7761** [comment]
Thanks for your reply. I may give it a look sometime. I've tried to interact with the taskbar before and found no real Win32 API for it. Mainly because in the past years it seems like a lot of bugs have crept into it. I think MS is no longer prioritizing back-compatibility, letting interns play fast and loose with the bedrock internals of the OS without much in the way of a review. (The bugs tend to linger for a year or two. It makes it look like software is misbehaving when it's really the taskbar layer.)

**Comment by the-a-man-006** [comment]
The Pressure/Dash-Docking idea would have been a great alternative... Nevermind.

**Comment by LuisThiamNye** [comment]
Closing as any future work will be done in Buttery Taskbar 2: https://github.com/LuisThiamNye/ButteryTaskbar2

(It's written in a much better language than C#.)

The thing about the pressure idea is that I'm not sure Windows gives me sufficient information to implement it without crazy town workarounds. The raw mouse input API would be the first place I'd look, but I haven't gotten familiar with that yet.
